### ISSUE TITLE
Microphones in DSPL and SSPL

### ISSUE THREAD

**Issue by komeisugiura** [RoboCupAtHome/RuleBook#216] opened 2017-01-12 09:19 UTC
I'd like to start discussions on microphones by the following two comments.

Section 5.3.4

I think 360-degree SSL is nearly impossible only from sound information by HSR's microphones. Since the microphones are linearly placed along with a 6-cm line segment, two sound sources whose positions are symmetrical about the line cannot be distinguished.

Section 3.4 and 5.3.6

The original recording data format of HSR is 16kHz, 16bit, 4ch, and little endian via ALSA (e.g. arecord command), which is different from the requirements (section 3.4).
I suggest to use this format for at least HSR.

**Comment by kyordhel** [comment] 2017-01-12 11:33
## Data Recording (S5.4 & S5.3.6)
Mi proposal on this subject is to completely remove all Data Recording subsections in the test chapters to reduce space and locate such information in another Appendix, with formats separated per sub-League, and just enumerating the data to be recorded per test.


## Speech [and Person] Recognition Test (S5.3.4)
First, allow me to state this two points

1. Sooner or later robots must be able to react to sound as we humans do, turning around when called to pay attention to the speaker. However, this doesn't mean that robots must be able to do 360° SSL, something we can't do either. Humans often turn around until visually identify the recognized speaker (if known), or to ask who was calling (if unknown).

2. If I understood it properly, @komeisugiura is telling us that the Toyota HSR won't be able to perform the test, and it seems to me (I beg your pardon) quite stupid to test robots in something we know they **can't** do, instead of testing what they can do.

Now, considering the previous points along with the statements made by @hideakin21 in #213, is easy to conclude that the *Speech [and Person] Recognition Test* is ill designed for the DSPL, and we till don't know about the SSPL. Therefore, it must be changed.

My proposal:
- Adapt the test so the robot can turn twice more times, while looking for the operator, and then listen to the question.
- Reduce the number of speakers to 4, located in a a square, so the robot only needs to guess if the operator is front, left, right or back.
- Completely remove the SSL part for DSPL and replace it with NLP questions (I wrote some examples in #202).
- Completely remove the SSL part for DSPL and make the robot to look for people (Person Recognition).

**Comment by komeisugiura** [comment] 2017-01-12 12:20
- Since using 16kHz is standard in ASR, I suggest to use 16kHz for OPL as well.
- HSR has four microphones. Pepper has four as well.
http://doc.aldebaran.com/2-0/family/juliette_technical/microphone_juliette.html
- I agree with putting more emphasis on the NLP (or Multimodal SLU, grounded language understanding, robot dialogs, or whatever) part for SPL robots.

**Comment by balkce** [comment] 2017-01-12 21:45
SSL was not well accomplished by many teams last year, and I would like to keep pushing for this functionality, considering that it is something that is useful for the Restaurant test. And, frankly, I don't like the idea that the limits of one platform limits the range of testing of another platform.

We can always apply a limit on where the persons can be located when HSR and Pepper are being tested. Based on the microphone positioning of both HSR and Pepper, 360 degree SSL is not possible, but a front 180 degree SSL is.

In addition, as discussed in #202 , SSL and NLP understanding is able to live within the same test. Actually, if time is an issue, I would go as far as completely removing the part of the tests in which the robot is asked from the list of specific questions, and make all the voice interaction based on the grammar/NLP part. Most teams did well in the specific-questions part of the test last year.

PS. Mau: humans are able to localize a sound source in the full 3D range. Try it out. The 3D sound synthesis concept used in video games is based on this.

**Comment by komeisugiura** [comment] 2017-01-13 08:32
I have the same opinion as @balkce about the usefulness of SSL. Also, I think the task is challenging enough so it does not have to be removed.

Therefore, I suggest to slightly change the rule so that SPL platforms can solve it, for instance permitting multiple (180-degree-)SSL executations as in @kyordhel 's first proposal.

**Comment by kyordhel** [comment] 2017-01-13 13:14
@komeisugiura, @balkce, if I understsnd this it right, robots can _know_ the speaker is to the Left or to the Right, at least in the front line. What happens _behind_ the robot?

I'm proposing the following 4 setups as in the figure.
![spr](https://cloud.githubusercontent.com/assets/8583949/21930973/28cf2d02-d999-11e6-8401-17daf507335e.png)
- [ ] **A**: Front, Back, Left, Right,  ~90° each.
- [ ] **B**: Three on the front line.
- [ ] **C**: Three on the front line, two on the back on each side.
- [ ] **D**: One in front, two behind, ~120° each.
- [ ] **E**: Two in front, one behind, ~120° each (**D** with robot turned 180°).

Please tell me which one is the best to test robots. Rulebook will be modified accordingly.

**Comment by balkce** [comment] 2017-01-13 16:01
I'd say: B for HSR and Pepper and either A or C for open platforms.

**Comment by HideakiNagano21** [comment] 2017-01-15 17:01
I think reducing the number of speakers and modifying their locations are good idea what I didn't have.

**Comment by komeisugiura** [comment] 2017-01-16 08:47
I’d think A and D are unattractive...
I like C for OPL, B/C for Pepper, and B for HSR.

**Comment by airglow** [comment] 2017-01-17 09:40
In my opinion we should use the same setup for all sub leagues. Wasn't it also a clear point that standard platforms should be modifiable in the call? Where is the problem with attaching an additional microphone array on the standard platforms? The Kinect also has just four linear attached microphones and there are transfer functions available for 3D SSL.

If we now differentiate already in Stage 1 tasks, this will lead to trouble in later games like restaurant, where the persons could potentially be localized by sound.

**Comment by komeisugiura** [comment] 2017-01-17 12:04
Any modification to an SPL robot is NOT allowed by the rule. Therefore, teams have to use its built-in microphones. Any additional sensor like a Kinect is not allowed.

The spirit of RoboCup@Home SPL is (and has been) to encourage teams to share the codes in the community from the moment we started the discussion. Introducing a team-specific additional device does not reflect this spirit.

**Comment by kyordhel** [comment] 2017-01-17 15:04
@komeisugiura & @balkce 
I will commit those changes during the week.

### Modifying SPL robots
About modified the SPL robots, I think the leagues are pretty clear. If a team wants to play with a modified Pepper/HSR is welcome in OPL. No further discussion on that for this is not matter for this issue.

### League differentiation
The main goal is that DSPL and SSPL aim to different objectives, as one of the objectives for OPL is grant absolute freedom in design. I am pursuing that each League has its own tests. Again this topic does not fir on this issue.

**Comment by bajsk** [comment] 2017-02-10 04:34
I have a question related to the modification of SPL robots. I have read the following content from the rule book.

> The idea of having standarized platform is to allow teams to compete in equality of conditions
by eliminating all hardware-dependent variables. Therefore, both Standard Platform Leagues
are considered as closed hardware design, meaning that and modifications and alterations to
the robots are strictly forbidden; including, but not limited to attaching, connecting, plugging,
gluing, and taping compontents into and onto the robot, as well as modifying or altering the
robot structure. Voiding this rule leads to immediate disqualification from the competition and
penalty for the team (see Section 3.9.2).
>
I understand no additional sensors like Kinect camera are allowed to be attached on the standard platform. However, as we use external laptop or PC to control the robot via arena network, is it OK to use different graphic cards attached to the external PC other than the internal Jetson TK1 equipped inside HSR?

**Comment by kyordhel** [comment] 2017-02-10 10:12
@bajsk As you mention no hardware of any kind can be attached to a SPL robot, so no Kinects are allowed. However, external computing devices are allowed (require TC inspection and approval) as stated in section **3.5 External Devices**. In detail:
- Teams may use any cloud service available online (e.g. Google Speech Recognition).
  - You use this technologies on your own risk.
- Teams may support their robots with external processing units (e.g. CUDA Cluster).
  - Interacting with external processing units is strictly forbidden.
  - External processing units must be inside the arena during the test.
- There is no guaranty of WiFi availability, stability, or reliability:
  - You use WiFi on your own risk.
  - Teams are not allowed to broadcast wireless networks.
  - Robots **must** be able to **operate when wireless** connection **is unavailable**.
  - EC/TC/OC takes no responsibility for network errors.
- All external devices must be listed in the TDP and approved by the TC during robot inspection.

Hope I've answered your question.

**Comment by warp1337** [comment] 2017-05-10 16:53
Regarding the wireless connection: At the German Open (SSPL and OPL) we discovered that a stable wireless infrastructure is essential. I also heart that the wireless setup for the RoboCup2017 is being tested right now. Tim from TU/e and me (Team ToBI) already had a quite good discussion at the German open about the wireless lan. So 1) Who can we share our experience with and 2) "Robots must be able to operate when wireless connection is unavailable" how is this doable on the HSR and the Pepper. I mean, yes, you can still do _some_ things, but accomplishing a full task without any external computation is extremely hard IMHO.

**Comment by balkce** [comment] 2017-05-10 17:05
@warp1337 I would open a new issue for your topic, since this thread is about microphone positioning and may not be easily found by the persons you're aiming your question at.

In addition, I would advise you to consider the comments of other persons that have acknowledge your issue before, such as #173 #128 and #243. They may be old, but it may provide some insight on why some ideas were rejected.

**Comment by balkce** [comment] 2017-05-10 17:06
I'm closing this issue since it has derailed into other topics, and it appears that the main objective has been covered.

**Comment by warp1337** [comment] 2017-05-10 17:06
@balkce Thx. Will do!

**Closed by balkce** 2017-05-10 17:06 UTC
Labels: Data recording, Speech & Person Recognition, Speech Recognition

**Comment by furushchev** [comment] 2017-05-24 08:59
@balkce  I think this issue should not be closed yet since the original problem (Current rules of SSL for is not suitable for standard platform robots) is not yet solved.

@kyordhel any update for this issue? As far as I can see in the conversation here, you are creating pull request to update the rules on it? ( https://github.com/RoboCupAtHome/RuleBook/issues/216#issuecomment-273193384 )

**Comment by kyordhel** [comment] 2017-05-24 09:02
@furushchev the issue is closed as all changes were reviewed and approved by @balkce and @LoyVanBeek in former merge.

**Comment by furushchev** [comment] 2017-05-24 09:12
@kyordhel How about the discussion above (https://github.com/RoboCupAtHome/RuleBook/issues/216#issuecomment-272440286), this is not yet merged into rulebook and no one discuss any more.
Should I create another issue?

**Comment by kyordhel** [comment] 2017-05-24 09:18
Pffffffffffffffff...
I'll do that.

**Comment by kyordhel** [comment] 2017-05-24 13:11
Addressed in #289 and #291 @furushchev
