### ISSUE TITLE
[DSPL] Official Standard Laptop for Toyota HSR (Ethernet wired)(**again**)

### ISSUE THREAD

**Issue by okdhryk** [RoboCupAtHome/RuleBook#368] opened 2017-11-13 11:45 UTC
Deadline: Thursday, November 30th, 2017

To the DSPL community:

Unfortunately #366 has closed
https://github.com/RoboCupAtHome/RuleBook/issues/366

Please let me suggest again using official standard laptop for HSR.

Members of 10 teams who participated in this year's competition should be strongly aware of the necessity of more powerful computing power.
I think that a new team that enters from the next year will feel its necessity if they actually use HSR.

In the original HSR there is a weak point in the ability of the built-in PC.
We can not fully implement the functions of object recognition or speech recognition.
This is boring for the audience and it is a major factor hindering the advancement of our research.

If it is difficult for all teams to purchase and use the same model,
Why do not you decide the upper limit of CPU and GPU capabilities?

Hiroyuki Okada
Team eR@sers, JAPAN

**Comment by tkelestemur** [comment] 2017-11-13 17:12
I strongly agree with you. Having an external backpack laptop will increase our success significantly. That being said, I think in the last issue, the problem was not finding a common model that can be bought everywhere. The problem was the lack of the participation in deciding the laptop model. I am not quite sure but there might be teams that do not follow Github issues for RoboCup. Also, @kyordhel mentioned 5  of 12 old teams + 9 candidates raised opinion but are 9 candidates aware of RuleBook repo? Should we expect them to raise opinion?

We can create a list of the proposed laptop models in an excel file with specs, prices, and availability and send it as an email to every participant. We can collect votes until the deadline. I can volunteer to do that if it makes sense to everyone.

**Comment by justinhart** [comment] 2017-11-13 17:19
I think that this is just diffusion of responsibility. Individual teams
don't feel the need to pipe up and assume that we're solving this.

Anyway, 1 step down from the latest laptop processor. 1 step down from the
latest Nvidia processor. That makes the laptop affordable. No team is going
to whine about spending $1400 on a laptop when they're shipping a crate
with a 500 lb robot in it to Canada.

**Comment by kyordhel** [comment] 2017-11-13 17:24
Thanks @okdhryk for continuing this discussion. I really hope you find consensus soon. Also thanks for the clarification about the number of teams (10 participants instead of 12, although we received 12 applications past year, hence my confusion), It is fixed now.

@tkelestemur All 2017 participants were invited to join the discussion in GitHub (issue #366) or via email (OC). No email was received other than @justinhart's. As of the EC, they expect a lot of interest from the community in this, specially if the laptop will be expensive ($2000+, also TOYOTA's proposal was to expand HSR's processing capabilities, not replacing the external computing devices).

**Comment by yhagiwara** [comment] 2017-11-14 02:05
Thank you for your suggestion. I agree to use the official standard laptop in the plan to decide the upper limit of CPU and GPU capabilities. I believe that strengthening computing power will contribute to higher-level human robot interaction by state-of-the-art machine learning methods.

Yoshinobu Hagiwara
Team Duckers, JAPAN

**Comment by tomshibata** [comment] 2017-11-14 05:20
Thanks @okdhryk. Yes, it is much better to have a stronger power compared to the original one. Having an external backpack laptop can also allow us not to use an external computer through WiFi, which can dramatically reduce problems which could be caused by WiFi on-site! I think we only need to restrict its size and weight.

**Comment by kyordhel** [comment] 2017-11-14 10:46
The limits set by TOYOTA are as follows:

- Dimensions:
  - Maximum height: 430mm
  - Maximum width: 430mm
  - Maximum thickness: 48mm
  - Maximum weight: 5.0kg

Additionally, the OC and EC have agreed in the following requirements:
- Available worldwide
- Budget friendly
- Must be 100% Linux compatible.
- Same ROS version as the HSR
- Laptop must fit in the backpack.

Please refer to #366 for detailed explanation

**Comment by MatthijsBurgh** [comment] 2017-11-14 10:57
Because this is a standard platform. The laptop should be equal for all teams. Ignoring this rule, breaks down the concept of this league: "Having the same hardware, so software can be interchanged without (nearly) any adaptations."

I find it very difficult to set a budget, because I don't know the budget of other teams.

I think the way to go is decided a budget first. Then people can search for the best performance for that budget.

One final note: I think it is impossible to find a laptop which is available worldwide. So we should find a solution which provides same specs.

**Comment by kyordhel** [comment] 2017-11-14 12:24
@MatthijsBurgh It is possible to have two (max three) official backpack laptops as long as they are equivalent (same processor, ram, gpu, battery life, etc).

**Comment by LoyVanBeek** [comment] 2017-11-14 12:46
Would it be an option to buy these via Toyota? Then the laptop doesn't have to be available all over the world, just in the place Toyota buys them for us and then ships them to the teams, maybe integrated into a neat backpack already.

**Comment by kyordhel** [comment] 2017-11-14 13:17
@LoyVanBeek It was already discussed with Toyota if they could provide teams with the official standard laptop along with the backpack itself. The answer was no. It seems all laptops would need to be imported to Japan, and then shipped to each team, something that might increase its price for up to 25% excluding import taxes in target country. In addition, the R&D division of Toyota wasn't authorized for that procedure.

**Comment by mnegretev** [comment] 2017-11-15 01:27
I agree with the idea of setting not a standard laptop but the maximum computing power. I also agree with @tkelestemur  with the idea of having an excel file with laptop options. If we have an idea of the laptops used by all teams, we can do a good choice about the max specs. The laptop we use is a Lenovo ThinkPad P50 with the following specs (which actually fits the size specs posted by @kyordhel ): 

* Processor Intel Core i7-6820hq 2.7 GHz
* 16 GB RAM
* GPU Nvidia Quadro M1000M
* Size 370 x 250 x 40 mm
* Weight 3.0 kg approx

**Comment by maximest-pierre** [comment] 2017-11-15 01:39
@mnegretev Currently the P50 was been replace by the P51. It should be the same laptop. Currently, our robot S.A.R.A. use the old P50 but with the Xeon processor and Quadro M2000M. It is a capable Laptop with excellent Linux support.

Here is the link to the new version:
https://www3.lenovo.com/us/en/laptops/thinkpad/thinkpad-p/ThinkpPad-P51/p/22TP2WPWP51?menu-id=P51

**Comment by argenos** [comment] 2017-11-15 21:09
@alex-mitrevski and I talked about it today, and we feel the same way as @MatthijsBurgh, namely that teams should preferably have the same laptop to keep the league `standard`. 

Our team is one of the candidates who has just been selected to receive an HSR. Since we have no experience with the robot yet, we don't have a good enough grasp of how much computing power is actually required to make an informed suggestion. 
Overall, our team would prefer to avoid paying windows tax and something in a reasonable range (under 2000€), but we don't know the actual limitations for our case and what is actually worth getting. From the options given, the suggested Dell laptops seem a reasonable combination in terms of delivery, specs, and budget.

**Comment by kyordhel** [comment] 2017-11-15 23:04
@argenos,

The HSR is powered by a nVidia Jetson TK1 according with [[1]](https://developer.nvidia.com/embedded/community/reference-platforms) and [[2]](https://robotstart.info/2016/10/28/gpu-jetson.html). Source [[3]](https://elinux.org/Jetson_TK1) says that it has a ARM quad-core Cortex-A15 CPU @2.32GHz, 2GB DDR3L plus NVIDIA Kepler GK20a GPU. I can't tell you about the performance of the TK1 but, for reference, I've seen robots performing quite good in the past with an Intel i7-Q720 which is also a quadcore [[4]](http://www.euroc-project.eu/fileadmin/Files/Challengers/RAM_2012_Home.pdf) with maybe twice as much RAM. That was enough to win the competition several times. As far as I know, no GPU or DRNN was used.

Regarding the price, the DSPL community will set it.

One aspect neither EC nor OC can be flexible with, is the standardization of the laptop. It will be logistically impossible for us to check the hardware of all teams during the competition, so we will check  that the laptop model matches our list of standard ones, and check in BIOS that the amount of RAM and CPU model/speed are the same.

In a standard league **all teams compete with exactly the same hardware**

**Comment by okadahiroyuki** [comment] 2017-11-15 23:42
Looking at the discussion so far, I think that there are two policies.
Why not start discussing after deciding which way of thinking to adopt as a policy?
## **Please tell us your opinion as to which one of A or B will be supported.**

(A)
>If it is difficult for all teams to purchase and use the same model,
>Why do not you decide the upper limit of CPU and GPU capabilities?
Do not decide the model of the PC, only decide on specs

(B)
>In a standard league all teams compete with exactly the same hardware
If this point is the most important, We need to choose a note PC that we can easily buy anytime anywhere in the world.
I and my team eR@sers strongly recommend selecting the following PC.
DELL Alienware 15
CPU: Core-i7 7820HK, 4.4GHz, 4cores, 8threads
RAM: DDR4 32GB
GPU: NVIDIA GeForce 1080, 8GB
Storage: SSD 1TB
Bandwidth: IEEE 802.11ac
Price: $3,124

**Comment by YutaroISHIDA** [comment] 2017-11-17 04:41
In our opinion, A is better if it's possible.
Because there are no model restrictions on the current External PC rule.

It is sufficient to have a size limit for safely mounting on HSR, and capabilities limit of CPU and GPU.

**Comment by mnegretev** [comment] 2017-11-17 05:01
Also in our opinion, A is a better option. I think it will be easier for all teams not to buy an specific model but just to respect the upper limits. I also think it will be more budget-friendly to specify the upper limit and not the exact model.

**Comment by yhagiwara** [comment] 2017-11-17 06:25
In our opinion, A is better. The reason is the same as @YutaroISHIDA .

**Comment by argenos** [comment] 2017-11-17 07:06
Definitely B. Two or three variations of laptops with the *same specs* is alright. Defining upper limits will cause variations in hardware that influence the results of the teams, the whole point of the **standard** leagues would be lost if the basis of comparison is different for each team.

**Comment by justinhart** [comment] 2017-11-17 07:52
I think that if we specify upper limits 1 step back from the current
mainstream upper limits, we'll be able to hit a very agreeable price point.
I agree that sourcing the same exact model world-wide would be challenging,
so I support option A, but I respect the wisdom of the other TC members who
have more experience on this front, and any rulings that the EC may make on
this violating standardization.

In the other thread I pointed out a couple of models. These are basically
what I mean. They're widely-distributed (I think you can get Dell anywhere
on the planet). They use the standard mobile cpus (I think that Xeon
options are too expensive). At the end of the day, every team will incur
much larger expenses than this to participate in RoboCup@Home, so I do not
think that this represents an excessive expense. This is especially true if
we step back to more modest models.

Alienware 17 with i7-7820HK & GeForce 1080 @ $2199.99
http://www.dell.com/en-us/shop/dell-laptops/alienware-
17/spd/alienware-17-laptop/dkcwkblf003destiny

We could push down the specs a bit and save the teams about $470.

Alienware 15 with i7-7700HQ & GeForce 1070 @ $1729.99
http://www.dell.com/en-us/shop/dell-laptops/alienware-
15/spd/alienware-15-laptop/dkcwkblf044s

**Comment by kyordhel** [comment] 2017-11-17 09:42
As OC Chair I want to make this statement clear,

**A is not an acceptable option.**

The Executive Committee already decided that for sake of standardization **all teams must have the same** laptop. Therefore, I invite @okadahiroyuki, @YutaroISHIDA @mnegretev, @yhagiwara, and @justinhart to decide over specs, reach consensus (as it was in the initial proposal), and then choose up to 3 equivalent laptop models for the teams to buy.

> *[I]n the case of standard platform league, different hardware among teams are not in the right direction[...] SPL means standardization, from my perspective even the OS inside the laptop should also be pre-installed and not changed, and it is also the case for all AIBO/NAO/Pepper robots. If you want flexibility, OPL is the right place to go.*

If you really don't like this decision, @mnegretev and @justinhart are TC members, so so feel free of taking this discussion back to the Execs and try to change their decision. Being that said, it is TC's duty to check that all DSPL backpacks match specifications (aka: no cheating), so is up to you.

**Comment by justinhart** [comment] 2017-11-18 04:42
I can agree with this. I meant your post when I said that I respect the
wisdom of the other TC members and rulings on the behalf of the EC, but I
couldn't find the initial post. I suppose I meant the OC, so, that's my
fault for mixing the two up.

I can get behind standardizing on just one laptop, or possibly 3 if there
is a real problem sourcing computers. If we're going with a large
manufacturer, the hardware should be basically the same worldwide. Dell
seems like an obvious choice from my desk in the US because I know that
they sell their stuff worldwide, but I'm happy to go with another
distributor.

Regarding specs, I stand behind my previous post. Xeons are too expensive.
GeForce GTX 1080s are inflated in price because they're the newest
hardware. The latest laptop chip is a waste of money because having the
newest stuff comes at a premium. If everyone gets a 1070 and an i7-7700HQ,
then we can guarantee performance that's pretty close to the best laptops
while getting a good bargain.

Regarding checking this, we can simply run dmesg, pump it into a script,
and look for all of the hardware entries.

If we get the Inspiron 15 7000 Gaming, then it costs $1200 and comes with
an i7-7700HQ and a GeForce GTX 1060. If we get the Alienware 15, we can get
the 1070, but it costs about $500 more. One note, if we get the Alienware
15, I think that it comes with some kind of contractual rider that dictates
that we must have a LAN party after the competition. It's cool, though,
Canada now has caffeinated Mountain Dew (they didn't until 2012), so,
technically we'll have all of the proper ingredients for our LAN party.
That said, I used to have an Alienware laptop as a PhD student and felt
really goofy giving a talk with a stylized alien skull on the back of my
laptop, so, maybe the Inspiron.

Justin

**Comment by SJ-YI** [comment] 2017-11-21 16:24
I am new to the @home league, but wasn't a external desktop (connected via wifi) allowed for the match? What was the rule for the server? I don't think every team have used exactly same desktop for the match.

**Comment by tkelestemur** [comment] 2017-11-21 19:03
@SJ-YI External computers are allowed but they are not feasible for the tasks where you need fast data stream (e.g. point cloud stream for motion planning).  Also, it is better to use on-robot face/speech recognition as it will reduce the time for interacting with humans.

**Comment by komeisugiura** [comment] 2017-11-22 12:27
Thank you all for your effort on the investigations of specs. 

Based on the discussions here, this topic is now discussed with EC (with suggestions from TC, OC chair and Toyota). 

Currently, there is no strong objections about the draft list, however we have to wait a little bit more. I'll let you know the result within one week.

**Comment by komeisugiura** [comment] 2017-11-29 10:42
Since there was no objections from EC (in the separate discussions),  I'd like to finalize the spec for RoboCup 2018. 

The standard additional laptop for RoboCup@Home DSPL 2018:

DELL Alienware 15 or 17
  - CPU: Core-i7 series
  - RAM: 16GB or 32GB
  - GPU: NVIDIA GeForce GTX 1070 or 1080
  - Storage: whatever

This does not mean the above spec is fixed forever. Instead, the spec will be discussed on yearly basis.

@kyordhel  can you please update the rulebook?

**Comment by kyordhel** [comment] 2017-11-29 11:47
@komeisugiura I'll update the rulebook accordingly and close this issue when finished.

**Comment by SJ-YI** [comment] 2017-11-30 08:18
So now the rule allows for two form factor (15 and 17 in), two GPU types (1070 and 1080) and broad range of memory and storage options. 

To me, it seems bit weird to specify the brand type (alienware) but leave most spec flexible. Shouldn't we allow for other equivalent laptops as well, as long as their spec are equal or below the standard one? 

I just checked the GTX 1070 equipped laptop pricing here and found that Alienware 15 w/1070 is almost $1000 more expensive than equivalent Clevo laptop in my country (same CPU, same GPU, roughly same size, no windows OS).

**Comment by komeisugiura** [comment] 2017-11-30 08:46
Spec-based approach is correct. However, to specify the brand makes the TC inspection easy. 

Please understand that in setup and competition days TC/OC/referees are super busy. If we allow Clevo, there will be no reasons to reject other minor PCs and we might have many variations of the laptops. If so, the TC/OC/referees will have to carefully watch that the additional laptops are intentionally or non-intentionally swapped with other PCs by teams, which is not efficient for organization.

Anyway, this is an EC decision, and we cannot include the Clevo laptop for 2018, sorry.

I'd say RoboCup 2018 is the first year to have the additional laptop in DSPL, so we are far from perfect.  To improve the procedure, let's have additional discussions after RoboCup 2018.

**Comment by kyordhel** [comment] 2017-12-15 17:21
Resolved in #374. Interested people, please review the changes and comment in the pull request.

**Closed by kyordhel** 2017-12-15 17:21 UTC
