### ISSUE TITLE
Wifi @Home

### ISSUE THREAD

**Issue by tik0** [RoboCupAtHome/RuleBook#95] opened 2015-05-06 15:16 UTC
Since more and more teams demand the usage of Wifi, I'd like to start a discussion about an official Wifi support for the @home league.
The status quo is actually not suitable, because every team uses it's own one and thus spamming all the channels.

For now, I see the following issues:

The authority:
- Some communication has to be done with the other (literally) surrounding leagues (soccer, etc.) beforehand, so that there will be no trouble spanning up the Wifi 
- There has to be a person/committee who demands the usage of the official Wifi and punishes teams, if they open up their own ones

The technician:
- There has to be one/two official technicians, who are in charge of the Wifi-AP
- The Wifi has to be set up such, that every team is able to use their own SSID and network setup
- During a task, the current team has the absolute priority of using the Wifi
- No Internet setup (Otherwise everyone would just log in with their smartphones)

The teams:
- The team leader has to hand in their setup configuration to the technician in charge
- The team leader is in charge of shutting down personal access points of the team members

Access point requirements:
- We need to buy one (So who has the money?)
- Multi SSID / Guest Networks capable running different setups
- 2,4/5 GHz
- n/ac running Greenfield mode
- MUMIMO (Multiple User / Multiple Input / Multiple Output)
- As much Client connections as possible
- External antennas for attaching Yagi antennas

**Comment by LoyVanBeek** [comment] 2015-05-06 17:02
Hey @tik0, we have also been thinking about this. 
We came with the following setup: 
- The TC sets up a official RoboCup@Home wireless network that every team connects with. 
- Each of the two arenas has its own access point, that use channel 1 & 6 so their frequencies don't interfere. 
- In the team area, anyone can setup an internet-enabled WiFi on channel 11, with low power as well. This may yield sucky internet because of interference, but the robots and challenges are more important. 
- The computers in the team area are connected via a switch or hub with the two arena access points. This limits the WiFi traffic to only the robots. Maybe each team gets its own subnet, that could maybe be handy. 
- Monitoring and managing traffic between teams and their robots is difficult, so we could just pull the cable that connects the teams to their robots during a challenge :smiley: 

TechUnited's MSL team brings a Wifi analyzer usually, we could use that as well to check whether there are any issues and APs that need to be 'managed'. 

At work, we have [Asus RT-AC66U](http://www.asus.com/Networking/RTAC68U/)'s which are really nice and have a ton of config options. Perhaps I can bring 2.

**Comment by kyordhel** [comment] 2015-05-06 17:42
I don't want to be the pessimistic guy here, but...

- What is proposed is not new, WiFi has been a problem since 2010
- To achieve this, a close communication with the Local Organization is required. It has never been achieved.
- Even for RockIn where WiFi was explicitly forbidden (since it was provided by the host and required for tests), it was a BIG issue and,
  - Teams didn't gave a single F and set up their own wireless routers
  - The infrastructure provided by the host was insufficient for the attending people
  - Robots couldn't communicate with the Wireless device during the test.

Plus, when you hire a company for providing the service, they assume average use of normal people with normal bandwidth consumption. No company will think that all the people which will connect to the wifi are Computer Freaks with a high demand of bandwidth and all of them will be using at least 3 devices (Laptop + tablet + smart phone). In mexico we provided the @Home wifi (which was not used) and people used their own WiFi because is easier to setup. Also, 1 Gigabit internet badwidth for the whole event and it was insufficient.

For what you propose we need certified hardware (which I'm not sure the local organization can provide) plus volunteers for tracking the illegal WiFi. We may add a penalty on the rulebook so:

    Any teams using an unauthorized WiFi device, will be automatically disqualified
    in the next scheduled test.

However, I don't see the Trustees giving their concent on that.

**Comment by LoyVanBeek** [comment] 2015-05-07 17:34
If we stick to only robots on WiFi, humans and their computers on cable, then there are only 20 robots at best, divided over 2 arenas. A decent access point should be able to handle this. 
All the other leagues also have an official wireless network, so why wouldn't @Home be able to do this as well.

**Comment by kyordhel** [comment] 2015-05-07 17:38
Oh! We are able as any other league and yes, any router should be capable of serving 20 clients.
But also I'm realistic. I don't see teams working in a wired network. Even if Access Points/Routers are confiscated, they know how to set up an Ad-hoc netwok using a computer, and they will. And if teams set up their own WiFi, there will be very difficult for us to make them use only the approved channel.

Date: Thu, 7 May 2015 10:34:44 -0700

**Comment by tik0** [comment] 2015-05-08 07:50
@LoyVanBeek : If you bring the two AC66 it would be awesome. We just need a technician who cares about the setup and serves every team rigtht.
We definitely need MAC filtering and guest-networks so that teams can not corrupt each other.
Do you run some WRT or the the stock software on it?

@kyordhel 
If you add the passage as proposed to the rule book, I think every team should be wisely enough to obey the rules. As you said, to use the "official" Wifi is absolutely no option. The hardware is maybe outdated or the technician is not able to setup an AP regarding our demands.

Reading the number of clients, I would be more pessimistic.
A standard consumer AP can maybe serve 8 or 16 clients via WIFI.
I do not know how the performance of the AC 66 is, but a Neatgear with similar pricing can handle up 32 clients.
I see that it has some radial antenna, so we should think about a Yagi or other beam forming antennas (they should just cost some dollars), to not interfere with other leagues and having optimal coverage in the arena.

**Comment by tik0** [comment] 2015-05-16 14:15
This thread is going to be pretty sleepy, so I just want to make some notable updates:

- I can bring a Asus RT-AC66U as well. But for now it is just the stock software.
- The available channels at 5Ghz are pretty rare in China: http://en.wikipedia.org/wiki/List_of_WLAN_channels
  - We should not mess with the chinese authorities and tell the other participants to obey the available channels
  - This makes even harder for us to support a functional WIFI at 5Ghz

At last some questions:
- Shall we use the proposed Wifi rules by Loy?
- How about beam forming antennas?

**Comment by LoyVanBeek** [comment] 2015-05-17 18:51
- As for the firmware on the device, maybe its possible to make a backup of a device with the original firmware and put that on the other device. Or just work with the non-stock firmware, which should also be functional because it would not have been put in there I suppose.
- 5 GHz has really really short range and I can image not all hardware of robots capable of handling it. We did a couple of tests with 5Ghz with the robots from work and that kinda sucks. Another lesson from there is that automatic Wifi access point switching is a big PITA. 2 access points, 2 different SSIDs to prevent this auto-switching
- Adhering to my rules: of course I say yes. But we have to get up this network ASAP in the setup-days and then test whether it works with the expected load. If not, we revert to the old situation.
- Beam forming to ~10 robots? Is that possible?

**Comment by kyordhel** [comment] 2015-05-18 09:08
Loy,

There are directional antennas that operate over a straight line (about 10m wide) but they are expensive and require proper mounting, powering and being setup as access point. 

The issue is how to get them

**Comment by LoyVanBeek** [comment] 2015-05-18 17:42
OK, so thats expensive and required expertise, of which we have neither in this regard :disappointed: 

I spoke with a Wifi-expert today, he said 5 GHz should work. I guess we just enable both and ask people to use 5 GHz instead of 2.4 GHz.

**Comment by tik0** [comment] 2015-05-19 14:00
@Loy So shall there be an official timeslot during setupdays, where each team can test their WIFI setup?

**Comment by LoyVanBeek** [comment] 2015-05-19 14:05
Maybe, but if we want to do load testing, then we need a bunch of teams in the arena at one single time. That will happen by itself during setup. 
I preferably have a couple of teams going at this at the same time, together maybe even during the setup days. 
I want to create a global schedule before the event anyways.

**Comment by kyordhel** [comment] 2015-05-19 16:34
Hate me!!!!

According to [this](http://www.simplewifi.com/antennabasics.html), the directional antennas operate in MILES (shortest is 2 miles which is about 3km), and there is a relation between dBi and distance.

However, there are some low-power directional antennas, for instance
- [this one of 8dBi is for 400m](http://www.dx.com/p/2-4ghz-8dbi-sma-high-gain-directional-panel-antenna-for-wifi-wireless-network-30046#.VVtib-T9phF)
- [this one is 5dBi double band] (https://www.asus.com/Networking/WLANT157/specifications/) and is available [here](http://www.amazon.com/Asus-WL-ANT-157-Antenna/dp/B005UBNJ48) 
- [this crap is home-made](http://www.instructables.com/id/Uni-Directional-WIFI-Range-Extender/)

**Comment by LoyVanBeek** [comment] 2015-05-19 17:22
We'll just have to use the normal, default antennas unless someone brings a bunch of usable ones.

**Comment by LoyVanBeek** [comment] 2015-06-08 07:56
@tik0 TechUnited is bringing a RT-N66U for the arena network.

**Comment by tik0** [comment] 2015-06-12 06:17
So only one Access Point?
Thus we need another one for the second arena, right?

**Comment by LoyVanBeek** [comment] 2015-06-13 12:37
Yes, you said you could bring another one?

**Comment by tik0** [comment] 2015-06-13 13:28
Right, I just packed a RT-AC66U.
Despite the AC ability it is pretty much the same.

**Comment by kyordhel** [comment] 2015-07-09 13:19
Just to keep track of this issue. What is the final decision? Is there something to be updated in the rulebook? Shall I close this issue?

**Comment by LoyVanBeek** [comment] 2015-07-09 20:40
The stuff in the rulebook still applies, we'll try to set it up.Our networking guy at TechUnited cnnot join us after alll unfortunately, but we'll try to set something up.

**Comment by tik0** [comment] 2015-07-09 21:00
I think it is still not closed, but all the discussions should be postponed to next week in china. We have at least already a plan, so let's see if we can realize it.

**Closed** 2015-07-21 14:34 UTC
Labels: General Rules
