### ISSUE TITLE
YCB ("standard") objects not available anymore

### ISSUE THREAD

**Issue by LeroyR** [RoboCupAtHome/RuleBook#728] opened 2020-03-06 09:32 UTC
FYI

From our YCB order:

>  P.S. Please note that some objects in the kit have been replaced due to
availability and will differ from the 3D model dataset. Details are
given at the top of this page:
https://www.uml.edu/Research/NERVE/YCB-Form.aspx

> Object ID 6, Master Chef Coffee can has been replaced with a Maxwell House coffee can 
> Object ID 47, Power Drill model LDX172C has been replaced with model BDCD8C
> Object ID 69, Magazine that featured a beach has been replaced with an issue featuring the Dalai Lama

also
> Note that the labels on some food products may vary slightly from product to product, but we do our best to reduce this variation.

**Comment by RemiFabre** [comment] 2020-03-06 11:26
Annoying :/ So this only affects 1 out of the 13 items selected for @Home: 
https://github.com/RoboCupAtHome/AtHomeCommunityWiki/wiki/Standard-Objects

Since some teams will buy the items after this change (we will), maybe the best option is to replace the "master chef can" by another unchanged YCB item for @Home?

**Comment by DavidPL1** [comment] 2020-03-06 11:40
> Annoying :/ So this only affects 1 out of the 13 items selected for @Home:
> https://github.com/RoboCupAtHome/AtHomeCommunityWiki/wiki/Standard-Objects
> 
> Since some teams will buy the items after this change (we will), maybe the best option is to replace the "master chef can" by another unchanged YCB item for @Home?

As a short term countermeasure that seems reasonable, but in long term the question arises how long it will take until none of the original objects are available.

**Comment by moriarty** [comment] 2020-03-24 16:13
As with any dataset relaying on consumer products, their availability may change.

This is common due to promotions throughout the year effecting the appearance of packaging, and styles changing regularly to keep consumers consuming. This is the same with IKEA objects too, they seem to change their juice glasses every time I break one and need a replace one.

Fortunately this is just one object for now.

The method used for collecting the data for the YCB dataset was published:
https://ieeexplore.ieee.org/document/7251504
Available here: http://berkcalli.com/publications/2015-CalliSinghWalsmanDollar.pdf

More references
https://journals.sagepub.com/doi/pdf/10.1177/0278364917700714
https://people.eecs.berkeley.edu/~pabbeel/papers/2014-ICRA-BigBIRD.pdf

Unfortunately BigBIRD and Google Scanning rigs are quite expensive. But the rigs are still located in Berkeley and somewhere in Mountain View so if objects need replacing I recommend reaching out to the original authors and collaborating on a replacement object.

**Comment by moriarty** [comment] 2020-03-24 16:16
> > Note that the labels on some food products may vary slightly from product to product, but we do our best to reduce this variation.

This is not a bug. This is just reality.

**Comment by LeroyR** [comment] 2020-03-25 08:37
> > > Note that the labels on some food products may vary slightly from product to product, but we do our best to reduce this variation.
> 
> This is not a bug. This is just reality.

Reality is that athome should **not** have "standard" objects as you will never have this in _at home_ scenarios.

I can only imagine the discussions with teams - models trained on the released (old) data while some other version of this "standard" is placed in the arena.

If we standardize objects we should make sure that they are available and "STANDARD" for **at least** a year of competition?!

**Comment by nickswalker** [comment] 2020-03-30 17:55
Most of what people have in their homes is mass manufactured. It's not uniform, but life is more standard than not

**Comment by moriarty** [comment] 2021-02-10 06:46
I'm closing this as the YCB standard object set is good enough... in reality announcing any standardized object set is more than the RoboCup@Home has done in any previous years, so if there is a little variation teams should be able to handle it.

**Closed by moriarty** 2021-02-10 06:46 UTC
Labels: Bug
