### ISSUE TITLE
Microphones and speakers for audience

### ISSUE THREAD

**Issue by HideakiNagano21** [RoboCupAtHome/RuleBook#222] opened 2017-01-15 17:51 UTC
Nagoya LOC are now planning to setup the audio environment to improve the audibility for the audience.
One of our planning is as follows,
![2en](https://cloud.githubusercontent.com/assets/20435510/21964750/a19c36e6-db95-11e6-91b7-802c961be3ba.png)
The external device and the access point are assembled _by each team_ if needed.

We will check the plan work or not in Japan Open in advance.

**Comment by LoyVanBeek** [comment] 2017-01-16 08:27
Do I understand correctly, you intend to stream the robot's audio digitally?
That might solve the issue of distributing devices to the robots and getting them back.

**Comment by komeisugiura** [comment] 2017-01-17 13:44
I'd like follow up @HideakiNagano21 's points and would like to summarize the points.
 
## Issues
- The audience cannot catch the spoken commands, and do not understand what's going on especially in GPSR, and other HRI-related tasks.
- Onboard microphones of HSR and Pepper are poor. There will be many cases where the audience is disappointed when almost all user utterances are misdetected/misrecognized/misunderstood by HSR or Pepper.

## Suggestion to LOC 
- LOC should provide official wireless microphone(s) connected to an audio mixer for DSPL/SSPL.
- When giving a command to a robot, the human commander is supposed to use the official microphone so that the utterances can be clearly heard via the venue's loudspeakers.

## Suggestions for rulebook (DSPL/SSPL only)
- An external speech processing device is allowed. The device is only allowed to connect the mixer's audio line out.
- The device can be used for sending the raw signal to the robot, processing it on the device, or sending the signal to a thirdparty's ASR service.

**Comment by komeisugiura** [comment] 2017-01-17 14:03
Here is a list of supplementary points came up in my mind.

- Attractiveness is important for the success of the whole RoboCup event.
- The President of RoboCup Federation came to our arena last year and said that the test is hard to understand without explanations.
- The rulebook says in Sec. 3.8.12 that the team has to provide a Moderator, however from my experience, this has been not working in most cases. Sometimes the Moderator stops talking to prevent the robot to fail to catch the utterances. With the external device, we don't have to care about such a case.
- OPL robots have better microphones, so we do not have to change the rule for OPL.

**Comment by LoyVanBeek** [comment] 2017-01-18 07:59
However much I like the idea, any loud noises or other speech during robot speech recognition will likely interfere if the robot can hear it too. 
Especially when doing Sound Source Localization with a loud speaker in a different position that the actual speaker. If I'd close my eyes, I'd be confused as well. 

In the past, we've decided we wanted to have the microphones on the robots, if I recall correctly. I would be OK with external microphones or operators speaking into a smartphone etc. if we allow this for all 3 leagues. 

Another suggestion to help the audience is to set up a TV with test description and when we can implement a refbox, show subtitles on the TV with what the robot heard.

**Comment by komeisugiura** [comment] 2017-01-18 11:51
### External speech devices
- I don't mean to deny to use the onboard microphones. My idea is to provide an additional way for SPL robots as an backup.
- By forcing the commander to use the official microphone, teams can choose either they process noisy speech obtained from onboard microphones, or clean speech obtained from the external device.
- SSL ability should be tested by the onboard microphones even in SPL

### Refbox (=official ASR engine)
- Most errors will be caused by voice activity detection (VAD), so it is unlikely the correct recognition results (subtitles) are obtained by the *robot*.
- Implementing the official refbox (=official ASR engine) is possible. The conditions are the following:
  - The refbox is connected to the mixer (next to the "external device" in the above figure).
  - When a commander gives a speech command, the direct sound can be directly processed by the robot if the team want.
  - At the same time, the speech is processed with the refbox and the result is shown on the subtitle on the screen.
  - It is likely the correct recognition results are obtained by the *refbox*.

**Comment by HideakiNagano21** [comment] 2017-01-29 21:28
I agree with @komeisugiura. The onboard microphone is allowed, of course. Besides, the official microphone shall be used in order to make the audience to catch what is spoken to the robot in DSPL and SSPL  not only for the audience but also the sponsor.
I've added some description regarding this #225

**Comment by furushchev** [comment] 2017-05-24 08:48
> By forcing the commander to use the official microphone, teams can choose either they process noisy speech obtained from onboard microphones, or clean speech obtained from the external device.

In my opinion, it's better to let each team choose not only which audio source they use but also whether commander use official microphone or speak directly to onboard microphone, because for teams that do not use official microphone and use onboard microphone instead, echo sound from speaker through officical microphone can be huge noise for speech recognition and sound localization.
In home environment there is no speaker and any person does not use microphone for speech, so existing system for home assistant robot will not be prepared so much for that environment.

**Comment by furushchev** [comment] 2017-06-14 03:47
@kyordhel @LoyVanBeek @HideakiNagano21 @komeisugiura Any update?

**Comment by LoyVanBeek** [comment] 2017-06-14 09:58
For the audio feedback, we try to get it so that the audience can understand it as well, so the external speakers. This should be understandable for the operator as well. In case there is a problem with the sound system, the robot should fallback to its own speaker, which should be simple to do by pulling out the audio plug. 

As for audio input, the team may choose.

**Comment by kyordhel** [comment] 2017-06-14 10:10
This is not topic for the Rulebook IMHO, as it depends on the equipment the LOC can get for the event. The external audio connector is mandatory since 2009, but has caused more logistic problems than advantages.

Many times teams have complained because the robots get confused with the echo, the external audio is used and the operator can't hear the robot, and so on. I am not forcing neither the LOC nor the teams to incorporate devices/streams which won't be used in home environment.

**Comment by furushchev** [comment] 2017-06-14 10:33
@kyordhel @LoyVanBeek Thank you very much for quick reply!
We do understand the practical reason why the official microphone is used during each tasks.
To clarify, we can use both officical microphone and on-board microphone, right?
If so I'd like to let us all identify the fact that echo voice from speaker through official microphone will strongly interfere the on-board microphone and I think it's not related if we plug out the audio connector from our robots / devices.

I write the comment as a participant who looked the rulebook:

@LoyVanBeek You said,

> In case there is a problem with the sound system, the robot should fallback to its own speaker, which should be simple to do by pulling out the audio plug.

but in the rulebook,

> Although using an on-board microphone is recommended in DSPL and
SSPL, using the following official microphone is allowed as a backup.

It mean that the recommended use case is we should use on-board microphone in normal and we can fallback to "official microphone" in case of some problem, right?
If so, my opinion is we should inspect the effect to on-board microphone when official microphone is used beforehand, because speech recognition is very important and has heavy weight on score sheet and we must retire on failure of speech recognition in some tasks.

Also, in the rulebook:

> The official microphone is used for the tasks inside the arena except SSL-related tests
(Speech and Person Recognition). Outside the arena, the official microphone is not
used.

This means that the official microphone is **NOT** used on:

- Between home and car in Help-me-carry task
- Restaurant task
- Speech and Person Recognition task

and during these task we must use **only** on-board microphone, right?
I think this is very complicating and confusing, it actually means that all team have to do:

- Prepare external computing that has microphone plug to connect official microphone and run speech recognition on the device
- Prepare on-board speech recognition too without official microphone
- Compensate there is no negative effect to on-board speech when official microphone is simultaneously used
- Implement fallback on any problem on each device (from on-board to official, or opposite)
    - Especially in Help-me-carry task, we must implement the fallback that switches from official microphone to on-board when robot and person is going outside.

**Comment by furushchev** [comment] 2017-06-14 10:42
I just want to confirm: I think my comments should be addressed also for Robocup **2017**.

**Comment by LoyVanBeek** [comment] 2017-06-14 10:52
@furushchev for the fallback, I was referring to the speakers, not the microphone. 
I have never dealt with an RoboCup-official micrphone, so here @HideakiNagano21 should clarify, as he wrote those rules. 

My main concern is that if the microphone or speakers, internal or official have issues causing the robot to fail, there's only so much we can do about it, especially during a challenge.

**Comment by kyordhel** [comment] 2017-06-14 10:54
Several remarks.

### Audio output plug and arena speakers
In previous competitions I was running after teams to fetch the RF transmitters for the speakers. With 3 arenas, 3 leagues, pipe-lined tests, and 2 OC members (the rest will be busy either as LOC or they are Team Leaders), there is no way I can make sure OC is taking care of audio devices. Past year in Leipzig the Referees/TC acted also as OC because there was only one available (the OC Chair), and we didn't had time for microphones.

### Official Microphone
The same as the former point. We are not chasing anyone to get the official microphone. If the team needs the microphone and it is not there, too bad for them. If they can't compete because of that, their problem.

### Test performance
We are taking no responsibility if the robot is deaf because it's out of reach of the Tx device, problems for low batteries, hardware incompatibilities, gain is too high/low, external computing device is too far so it can't do audio processing, internet connectivity problems, etc.

**Comment by furushchev** [comment] 2017-06-14 12:58
@LoyVanBeek @kyordhel Thank you very much for opinion!

@HideakiNagano21 How do you think of this issue?

**Comment by furushchev** [comment] 2017-06-14 13:14
@LoyVanBeek 
> @furushchev for the fallback, I was referring to the speakers, not the microphone.

Sorry, I thought it was about microphone thank you!
And please note that in Japan Open 2017, this was not allowed.
(Speakers **MUST** use official microphone and speaker during tests even if team members claim that they use on-board microphone)

**Comment by komeisugiura** [comment] 2017-06-14 16:23
We will be able to prepare the official microphone in Help-me-carry and Restaurant as well. Since processing the official microphone's signal requires an external device, this topic is related to a stable wifi system and the layout. Therefore, please let me spend some more time to finalize them before the audio system.

By the way, some DSPL teams might use rospeex for speech recognition. They can connect rospeex from the venue as is. They can also connect "rospeex@home", in which the server is placed on site and there is almost no delay. This structure was tested by four out of seven DSPL teams in Japan Open, and worked well.

**Comment by furushchev** [comment] 2017-06-29 14:43
@HideakiNagano21 ping to the author of this issue

**Comment by furushchev** [comment] 2017-07-07 06:11
@HideakiNagano21 ping

**Comment by kyordhel** [comment] 2017-07-10 12:23
@komeisugiura any update on this topic or shall I close the issue?

**Comment by komeisugiura** [comment] 2017-07-10 13:21
The layout has been 99% done, and I started to finalize the audio system. 

There are official microphones for DSPL and SSPL. The conditions are as follows:
- Team should provide an external device which has a female 3.5mm audio adapter (headphone jack)
- The input is MIC IN (not LINE IN) 

DSPL/SSPL teams can choose to either the official mic or on-board microphone. Please note that high-quality noise reduction and reverberation reduction will be required if you want to use on-board microphones.

For OPL robots, the situation is the same as last year.

**Comment by LoyVanBeek** [comment] 2017-07-10 14:52
OK. BTW: I e-mailed @HideakiNagano21 a couple of days ago to urge a response (after @furushchev's 2nd ping) and he responded he would respond soon.

I hope @komeisugiura's response is satisfactory?

**Comment by furushchev** [comment] 2017-07-10 15:30
@LoyVanBeek @komeisugiura @kyordhel Thank you very much for response!

I wonder in the current latest rulebook, official microphone cannot be used (see https://github.com/RoboCupAtHome/RuleBook/issues/222#issuecomment-308392159 for detail) and already the rulebook was fixed.
Is this an exception? If so, we should update a rulebook and share this information to all participants immediately via mailing list since this is very big change for all teams. (All teams **MUST** bring at least one external computing)
I cannot help but feel disappointed about it that this important discussion is inactive so long almost just before the competition....

**Comment by komeisugiura** [comment] 2017-07-10 15:49
The rulebook says on-board microphones are "recommended", but not a MUST. This is introduced since in the early years (-2009), where some teams used wired microphones.

Using the official microphone is NOT a MUST for DSPL/SSPL robots. Using the official microphone is MUST for the HUMAN speaker (to be understood by audience) only in DSPL/SSPL. 

I think the rulebook is okay. Teams can choose.

**Comment by kyordhel** [comment] 2017-07-10 16:06
### Mandatory external computing / audio plug

Just to clarify,

As Komei already pointed out, neither this is a *«very big change»*, not teams «**MUST**» provide external computing compulsorily. Rulebook's section 3.5 (External Devices) subsection 9 and 10 state:

> 9. **External device for audio processing:** An external speech processing device is allowed. The device is only allowed to connect the mixer’s audio line out. The device can be used for sending the raw signal to the robot, processing it on the device, or sending the signal to a third-party’s ASR service.
> 10. **External microphones:** External microphones, hand microphones, and headsets are not allowed in OPL. Although using an on-board microphone is recommended in DSPL and SSPL, using the following official microphone is allowed as a backup. 
    - **DSPL/SSPL only:** In order to make the audience to catch what is spoken to the robot, the speaker is supposed to use the official microphone to speak to the robot. The official microphone is used for the tasks inside the arena except SSL-related tests (Speech and Person Recognition). Outside the arena, the official microphone is not used.

Two weeks before the competition, most teams must be busy buffing their tests or already packed the robot and send it to have time to go through customs. Therefore I think it would be irresponsible to make mandatory any use of microphone.

Even more. If the team is not willing to use the official microphone, I'm fine with that. I've seen in the past a couple of tests failing because the external audio failed (Tx batteries drained, volume was too low, the plug was loose and the module went deadlock, etc) and teams were outrageous. 

### Rulebook amendments and team notification
As @LoyVanBeek and I have already discussed, is quite easy to request changes to the rulebook, but when it comes to actually write it, people is not that enthusiastic. Shall any change be made to the rulebook, I would gladly review any incoming pull request.

**Comment by komeisugiura** [comment] 2017-07-12 07:17
It might be off topic, but the following is the current version of @home area. The furniture and low walls are not (and will not be) shown.
[layout_athome_v10_p2.pdf](https://github.com/RoboCupAtHome/RuleBook/files/1141170/layout_athome_v10_p2.pdf)

**Comment by LoyVanBeek** [comment] 2017-07-12 07:38
@komeisugiura Awesome. I'll add it to the Nagoya 2017 repository

**Comment by furushchev** [comment] 2017-07-23 11:16
I still cannot understand the conclusion of this issue at all.

In the rule book, using official microphone is not allowed outside arena ( https://github.com/RoboCupAtHome/RuleBook/issues/222#issuecomment-308392159 ), therefore, we cannot use officical microphone from the entrance of arena to car in help-me-carry task and entire restaurant task.
However, @komeisugiura says it can be used (  https://github.com/RoboCupAtHome/RuleBook/issues/222#issuecomment-308484160 ).
Please could you clarify this point?

**Comment by furushchev** [comment] 2017-07-23 11:19
> OK. BTW: I e-mailed @HideakiNagano21 a couple of days ago to urge a response (after @furushchev's 2nd ping) and he responded he would respond soon.

Why no response at all from @HideakiNagano21 for this issue????? I totally cannot believe the current situation. It's only couple of days left to the competition!!

**Comment by kyordhel** [comment] 2017-07-23 12:19
@furushchev  don't over stress about this, OK? Please.

Focus in having your test running smoothly. If there is microphone and your robot can benefit from it, we will use it, otherwise we will skip it. Won't be the first time (nor the last) we jump over the official audio because it causes more harm than benefit to robots performance.

Considering many teams already are on it way to Nagoya (or are already there) and haven't had access to their robots for more than one week, whatever is decided here is irrelevant for the competition. The EC/TC/OC will override rules at the place as needed.

**Closed by kyordhel** 2017-07-23 12:19 UTC

**Comment by furushchev** [comment] 2017-07-23 12:56
@kyordhel 
Who stress about this? I already wait for **2 months**. We just want to clarify everything for the competition in this public place. I believe it is far better fairplay (as written in rulebook) than other closed meetings. it's totally unkind for newbies....

**Comment by kyordhel** [comment] 2017-07-23 16:52
Before the rulebook was moved to GitHub and made public in 2014, the discussion of the rules was closed within the TC and the only feedback teams had (newbies or not) was the draft (often published three or four months before the competition), the final version (often published at most a couple of months before the competition), and the Team Leader meetings during the competition. I kindly suggest you to consider this before calling rude (or unkind) to any EC/TC/OC member. You are always welcome to join the OC and fix all those situations you complain about.

Now talking as OC Chair, any questions related to the logistics during the competition will be answered during the first Team Leader meeting in Nagoya, as it would be unfair to explain things while most teams are in transit.
